[[Introduction]]
== Application Areas

Development of an information framework requires understanding of the applications that the framework should support. The following application areas are included in this document:

* Climate Health
* Healthy Aging
* Global Indicators
* Health in the Smart City

include::application-areas/climate-health.adoc[]

include::application-areas/healthy-aging.adoc[]

include::application-areas/global-indicators.adoc[]

include::application-areas/health-in-the-smart-city.adoc[]


=== Scenarios

#please add your scenario here#

== Disaaster Resilience Scenarios

*Sendai Framework for Disaster Risk Reduction* 

The UN General Assembly Resolution A/RES/71/276 (cite:[RN756]) endorsed the recommendations of the Open-ended intergovernmental expert Working Group on 2 February 2017. The report recommends indicators for the seven global targets of the Sendai Framework for Disaster Risk Reduction 2015-2030 (cite:[RN757]. The indicators related to health are as follows:

_Sendai Framework Indicators Related to Health_
[source]
--
- Global target A: Substantially reduce global disaster mortality by 2030, aiming to lower average per 100,000 global mortality between 2020-2030 compared with 2005-2015.
   - A-1 (compound) Number of deaths and missing persons attributed to disasters, per 100,000 population.
   - A-2 Number of deaths attributed to disasters, per 100,000 population.

- Global target B: Substantially reduce the number of affected people globally by 2030, aiming to lower the average global figure per 100,000 between 2020-2030 compared with 2005-2015.
   - B-2 Number of injured or ill people attributed to disasters, per 100,000 population.
   - B-3 Number of people whose damaged dwellings were attributed to disasters.
   - B-4 Number of people whose destroyed dwellings were attributed to disasters.
   - B-5 Number of people whose livelihoods were disrupted or destroyed, attributed to disasters.

- Global target D: Substantially reduce disaster damage to critical infrastructure and disruption of basic services, among them health and educational facilities, including through developing their resilience by 2030.
   - D-2 Number of destroyed or damaged health facilities attributed to disasters.
   - D-7 Number of disruptions to health services attributed to disasters
--

However, the quality of these indicators is constrained by the quality of the data used to generate them (cite:[RN767]). When high-quality data is accessible, differences in recording can frustrate attempts at aggregation, and even when aggregation is possible, significant subgroup trends can sometimes be masked. As the authors note, the  World Health Organization (WHO) Global Reference List of 100 Core Health Indicators is a step toward alignment in reporting.

The Framework and any supporting OGC Innovation Program activities should take advantage of the momentum established by these 100 indicators.

A complementary asset is available from the http://www.healthdata.org/gbd[Global Burden of Disease (GBD)] research program. The GBD provides a helpful decision-support tool, the https://vizhub.healthdata.org/gbd-compare/[GBD Visualization Hub], particularly with respect to Sendai Framework Global Targets A and B. The Hub is maintained by the http://www.healthdata.org/about[Institute for Health Metrics and Evaluation (IHME)] at the University of Washington in Seattle, USA. It provides consistent, comparative descriptions of the burden of diseases and injuries (and associated risk factors), including categorization of deaths and disability adjusted live years due to a breadth of causes.

Another complementary tool is provided by http://www.inform-index.org/[INFORM] (INdex FOr Risk Management), a global, open-source risk assessment for humanitarian crises and disasters. It can be used to support decisions about prevention, preparedness and response. Of particular note are the http://www.inform-index.org/Results/Global[data and calculation steps] showing:

* Risk of humanitarian crises and disasters;
* 5 year trends in risk;
* Where has risk increased most; and
* Prioritization using risk level and trends.
